spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeOfLife: 60000
  data:
    mongodb:
      database: coderhouse
      host: localhost
      port: 27017
      authentication-database: admin
      password: admin
      username: myUserAdmin
  mail:
    host: smtp.gmail.com
    port: 587
    username: matias.cermak9@gmail.com
    password: Matrox32
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


jwt:
  expiration: 1800000
  secret: springbootjwtcoderhouse
server:
  port: 9090
