spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    timeOfLife: 60000
  data:
    mongodb:
      database: coderhouse
      host: localhost
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 587
    username: cuentacoderhousemail@gmail.com
    password: Spartan1777
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expiration: 1800000
  secret: springbootjwtcoderhouse
server:
  port: 9090
